name: factories_minimal_report
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-edge.105ed2c11a78ffb22523edce372b1b13b56cd4fe

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  macros: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
